# Generated by Django 3.2.8 on 2021-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='albums',
            field=models.ManyToManyField(null=True, to='photo.Album'),
        ),
    ]
